version: "2.0"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_dev
    environment:
      POSTGRES_DB: gitfrank_dev
      POSTGRES_USER: gitfrank_user
      POSTGRES_PASSWORD: gitfrank_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gitfrank_user -d gitfrank_dev"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  postgres_data:
