version: "2.0"
services:
  git-frank:
    restart: always
    container_name: git-frank
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - /home/ubuntu/data:/data
    ports:
      - "4000:4000"
      - "1022:1022"
