version: "2.0"
services:
  git-frank:
    restart: always
    container_name: git-frank
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - /home/ubuntu/data:/data
      - /home/ubuntu/ssh-keys:/app/ssh-keys:ro
    ports:
      - "4000:4000"
      - "1022:1022"
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.0/24"
